DRL:
  Learn:
    actions: 2  # number of valid actions
    batch: 32  # size of minibatch
    frame_per_action: 5
    cuda: True
    ckpt_load: True
    gmma: 0.99
    input_image_size: 80
    action_type: 'discrete'

DEG:
  Learn:
    name : 'flappybird'  # 'main'
    cuda : True
    max_iter: 500000 # 2000000
    batch_size: 32
    image_length : 128
    image_width : 128
    print_iter : 10000
    z_dim: 16  # 'dimension of the representation z'
    num_workers : 2
    dset_dir: '../example_data'
    image_type: 'origin'

  MONET:
    lr: 0.00001
    num_slots: 3
    z_dim: 16
    ckpt_dir : '../saved_models/DEG/flappybird/'
    output_dir: '../saved_models/DEG/flappybird/'
    ckpt_save_iter: 10000
    beta: 0.5
    gamma: 10
    output_save: True

  CMONET:
    lr: 0.00001
    num_slots: 3
    z_dim: 16
    ckpt_dir: '../saved_models/DEG/flappybird/'
    output_dir: '../saved_models/DEG/flappybird/'
    ckpt_save_iter: 10000
    beta: 0.5
    gamma: 10
    output_save: True
    condition_size: 3

Mimic:
  Learn:
    cuda : True
    num_simulations: 10000001
    replay_memory_size: 10000
    episodic_sample_number: 1000  # the number of selected data points
    mcts_saved_dir: 'saved_models/DRL-interpreter-model/MCTS/flappybird/tree_models/mcts'
    max_k: 48 # number of latent dimensions

